unet:
  in_channels: 3                      # Number of input channels (e.g., for RGB image)
  out_channels: 3                     # Number of output channels (e.g., for binary segmentation)
  conv_channels: [64, 128, 256, 512]  # Number of channels in each convolutional layer
  kernel_size: 3                      # Kernel size for convolutional layers
  padding: 1                          # Padding size for convolutional layers