reproduce:
  seed: 42

image:
  width: 128    # resize to small picture
  height: 128   # resize to small picture

dip:
  backbone_name: "segnet"
  num_steps: 2000
  optimizer: "Adam"
  learning_rate: 0.001
  device: "cuda"

ddpm:
  scheduler: "cosine"
  beta_start: 0.0001
  beta_end:  0.02
  num_time_steps: 1000

guide-dip:
  count: 20
  start_t: 500
  end_t: 40
  num_steps: 2000
  backbone_name: "segnet"
  optimizer: "Adam"
  learning_rate: 0.001
  device: "cuda"