reproduce:
  seed: 42

image:
  width: 128    # resize to small picture
  height: 128   # resize to small picture

dip:
  backbone_name: "unet"
  num_steps: 200
  optimizer: "Adam"
  learning_rate: 0.01
  device: "cpu"
  num_snapshots: 9

ddpm:
  backbone: "unet"
  epochs: 100

pre-ddpm:
  backbone: "unet"
  epochs: 100