reproduce:
  seed: 42

image:
  width: 128    # resize to small picture
  height: 128   # resize to small picture

dip:
  backbone_name: "unet"
  num_steps: 200
  optimizer: "Adam"
  learning_rate: 0.01
  device: "cpu"
  num_snapshots: 9

ddpm:
  beta_start: 0.0001
  beta_end:  0.02
  num_time_steps: 1000