reproduce:
  seed: 42

image:
  width: 128    # resize to small picture
  height: 128   # resize to small picture

dip:
  backbone_name: "unet"
  num_steps: 300
  optimizer: "Adam"
  learning_rate: 0.001
  device: "cpu"

ddpm:
  scheduler: "linear"
  beta_start: 0.0001
  beta_end:  0.02
  num_time_steps: 1000

guide-dip:
  count: 10
  start_t: 300
  end_t: 40
  num_steps: 800
  backbone_name: "unet"
  optimizer: "Adam"
  learning_rate: 0.001
  device: "cpu"